<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60103030f3d21',
	'title' => 'Page Builder',
	'fields' => array(
		array(
			'acfe_flexible_advanced' => 1,
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 1,
			'acfe_flexible_layouts_settings' => 1,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 1,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 1,
			'acfe_flexible_toggle' => 1,
			'acfe_flexible_close_button' => 1,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 1,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '1',
				'acfe_flexible_modal_title' => 'Add Module',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => '1',
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_6010307841842',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_6010307f1033f' => array(
					'key' => 'layout_6010307f1033f',
					'name' => 'hero',
					'label' => 'Hero ',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_601033e041843',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => 'wp',
							'acfe_thumbnail' => 0,
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_6010340441844',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_6010340d41845',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => array(
						0 => 'Hero',
					),
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60103ae3d7be0' => array(
					'key' => 'layout_60103ae3d7be0',
					'name' => 'column_1',
					'label' => '1 Text Column',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60103b49d7be1',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60103c86d7be3' => array(
					'key' => 'layout_60103c86d7be3',
					'name' => 'column_2',
					'label' => '2 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60103c86d7be4',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60104135e8143' => array(
					'key' => 'layout_60104135e8143',
					'name' => 'column_3',
					'label' => '3 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60104135e8144',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => array(
								'acfcloneindex' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => array(
										'acfcloneindex' => array(
											'acfe_settings_setting_type' => 'required',
											'acfe_settings_setting_name' => '',
											'acfe_settings_setting_operator' => 'true',
											'acfe_settings_setting_value' => '',
										),
									),
								),
							),
							'acfe_validate' => array(
								'acfcloneindex' => array(
									'acfe_validate_location' => '',
									'acfe_validate_rules_and' => array(
										'acfcloneindex' => array(
											'acfe_validate_function' => 'value',
											'acfe_validate_operator' => '==',
											'acfe_validate_match' => '',
										),
									),
									'acfe_validate_error' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_6010413ee8145' => array(
					'key' => 'layout_6010413ee8145',
					'name' => 'column_4',
					'label' => '4 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6010413ee8146',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => array(
								'acfcloneindex' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => array(
										'acfcloneindex' => array(
											'acfe_settings_setting_type' => 'required',
											'acfe_settings_setting_name' => '',
											'acfe_settings_setting_operator' => 'true',
											'acfe_settings_setting_value' => '',
										),
									),
								),
							),
							'acfe_validate' => array(
								'acfcloneindex' => array(
									'acfe_validate_location' => '',
									'acfe_validate_rules_and' => array(
										'acfcloneindex' => array(
											'acfe_validate_function' => 'value',
											'acfe_validate_operator' => '==',
											'acfe_validate_match' => '',
										),
									),
									'acfe_validate_error' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60115329ea8d9' => array(
					'key' => 'layout_60115329ea8d9',
					'name' => 'hero_slider',
					'label' => 'Hero Slider',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_601153d360bef',
							'label' => 'Slide',
							'name' => 'hero_slider',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_repeater_stylised_button' => 1,
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Slide',
							'acfe_settings' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_6011555260bf5',
									'label' => 'Background Image',
									'name' => 'background_image',
									'type' => 'image',
									'instructions' => 'If there is an image in this field, it will show in place of the video',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'uploader' => 'wp',
									'acfe_thumbnail' => 0,
									'return_format' => 'url',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
								),
								array(
									'key' => 'field_601197fb54c99',
									'label' => 'Background Video',
									'name' => 'background_video',
									'type' => 'file',
									'instructions' => 'If there is a video in this field, it will show in place of the image',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'uploader' => 'wp',
									'return_format' => 'url',
									'library' => 'all',
									'min_size' => '',
									'max_size' => 150,
									'mime_types' => '.mp4',
									'acfe_settings' => '',
									'acfe_validate' => '',
								),
								array(
									'key' => 'field_6011989054c9b',
									'label' => 'Content Position',
									'name' => 'content_position',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'top-left' => 'Top Left',
										'top-center' => 'Top Center',
										'top-right' => 'Top Right',
										'center-left' => 'Middle Left',
										'center' => 'Middle',
										'center-right' => 'Middle Right',
										'bottom-left' => 'Bottom Left',
										'bottom-center' => 'Bottom Center',
										'bottom-right' => 'Bottom Right',
									),
									'default_value' => false,
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'return_format' => 'value',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_6011555d60bf6',
									'label' => 'Heading',
									'name' => 'heading',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
								),
								array(
									'key' => 'field_6011984354c9a',
									'label' => 'Heading Animation',
									'name' => 'heading_animation',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'fade' => 'Fade',
										'scale-up' => 'Fade & Scale Up',
										'scale-down' => 'Fade & Scale Down',
										'slide-top' => 'Slide Top',
										'slide-bottom' => 'Slide Bottom',
										'slide-left' => 'Slide Left',
										'slide-right' => 'Slide Right',
										'kenburns' => 'Scale Slowly No Fade',
									),
									'default_value' => false,
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'return_format' => 'value',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_60119ea754ca0',
									'label' => 'Animation Delay',
									'name' => 'heading_animation_delay',
									'type' => 'text',
									'instructions' => '1000 = 1 Second',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => 500,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
								),
								array(
									'key' => 'field_6011556260bf7',
									'label' => 'Paragraph',
									'name' => 'paragraph',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'acfe_settings' => array(
										'acfcloneindex' => array(
											'acfe_settings_location' => '',
											'acfe_settings_settings' => array(
												'acfcloneindex' => array(
													'acfe_settings_setting_type' => 'required',
													'acfe_settings_setting_name' => '',
													'acfe_settings_setting_operator' => 'true',
													'acfe_settings_setting_value' => '',
												),
											),
										),
									),
									'acfe_validate' => array(
										'acfcloneindex' => array(
											'acfe_validate_location' => '',
											'acfe_validate_rules_and' => array(
												'acfcloneindex' => array(
													'acfe_validate_function' => 'value',
													'acfe_validate_operator' => '==',
													'acfe_validate_match' => '',
												),
											),
											'acfe_validate_error' => '',
										),
									),
								),
								array(
									'key' => 'field_60119e7654c9f',
									'label' => 'Paragraph Animation',
									'name' => 'paragraph_animation',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'fade' => 'Fade',
										'scale-up' => 'Fade & Scale Up',
										'scale-down' => 'Fade & Scale Down',
										'slide-top' => 'Slide Top',
										'slide-bottom' => 'Slide Bottom',
										'slide-left' => 'Slide Left',
										'slide-right' => 'Slide Right',
										'kenburns' => 'Scale Slowly No Fade',
									),
									'default_value' => false,
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'return_format' => 'value',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_60119ec854ca1',
									'label' => 'Animation Delay',
									'name' => 'paragraph_animation_delay',
									'type' => 'text',
									'instructions' => '1000 = 1 Second',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => 500,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
								),
							),
						),
						array(
							'key' => 'field_6011a6f986dd3',
							'label' => 'Page Load Animation',
							'name' => 'page_load_animation',
							'type' => 'select',
							'instructions' => 'Animation to display when the page has loaded',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'fade' => 'Fade',
								'scale-up' => 'Fade & Scale Up',
								'scale-down' => 'Fade & Scale Down',
								'slide-top' => 'Slide Top',
								'slide-bottom' => 'Slide Bottom',
								'slide-left' => 'Slide Left',
								'slide-right' => 'Slide Right',
								'kenburns' => 'Scale Slowly No Fade',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_60119b8c54c9e',
							'label' => 'Animation Delay',
							'name' => 'page_load_animation_delay',
							'type' => 'text',
							'instructions' => '1000 = 1 Second',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => 500,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => array(
						0 => 'Hero',
					),
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Module',
			'min' => '',
			'max' => '',
			'acfe_settings' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-page-builder.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'featured_image',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1611769764,
));

endif;