<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d91fabd0287c',
	'title' => 'Module: cta-4-circles',
	'fields' => array(
		array(
			'key' => 'field_5d91faf8c1b39',
			'label' => 'Links',
			'name' => 'links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 2,
			'max' => 4,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d91facec1b37',
					'label' => 'Background image',
					'name' => 'background_image',
					'type' => 'image_aspect_ratio_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'aspect_ratio_width' => 800,
					'aspect_ratio_height' => 800,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
					'crop_type' => 'aspect_ratio',
				),
				array(
					'key' => 'field_5d91fadfc1b38',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'return_format' => 'array',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d91fb1bc1b3a_field_5d80f56b4dec1',
					'label' => 'Brand colours',
					'name' => 'brand_colours',
					'type' => 'color_palette',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'#233a80' => 'Brand one',
						'#67b2ce' => 'Brand two',
						'#acd3de' => 'Brand three',
						'#69b171' => 'Brand four',
					),
					'default_value' => '#315d98',
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'readonly' => 'readonly',
					'_clone' => 'field_5d91fb1bc1b3a',
					'__key' => 'field_5d80f56b4dec1',
					'__name' => 'brand_colours',
					'__label' => 'Brand colours',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 43,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'cta' => 'CTA',
	),
	'modified' => 1615765457,
));

endif;