<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60103030f3d21',
	'title' => 'Page Builder',
	'fields' => array(
		array(
			'acfe_flexible_advanced' => 1,
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 1,
			'acfe_flexible_layouts_settings' => 1,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 1,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 1,
			'acfe_flexible_toggle' => 1,
			'acfe_flexible_close_button' => 1,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 1,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '1',
				'acfe_flexible_modal_title' => 'Add Module',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => '1',
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_6010307841842',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_601bd8fddec76' => array(
					'key' => 'layout_601bd8fddec76',
					'name' => 'hero_slider',
					'label' => 'Hero Slider',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_601bd90edec77',
							'label' => 'Clone',
							'name' => 'clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_601bd6ffef5ee',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_settings' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => array(
						0 => 'Hero',
					),
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_601bdb12f69f5' => array(
					'key' => 'layout_601bdb12f69f5',
					'name' => 'hero',
					'label' => 'Hero',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_601bdb19f69f6',
							'label' => 'Clone',
							'name' => 'clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_601bd977c1cde',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_settings' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => array(
						0 => 'Hero',
					),
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60103ae3d7be0' => array(
					'key' => 'layout_60103ae3d7be0',
					'name' => 'column_1',
					'label' => '1 Text Column',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60103b49d7be1',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60103c86d7be3' => array(
					'key' => 'layout_60103c86d7be3',
					'name' => 'column_2',
					'label' => '2 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60103c86d7be4',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60104135e8143' => array(
					'key' => 'layout_60104135e8143',
					'name' => 'column_3',
					'label' => '3 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_60104135e8144',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => array(
								'acfcloneindex' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => array(
										'acfcloneindex' => array(
											'acfe_settings_setting_type' => 'required',
											'acfe_settings_setting_name' => '',
											'acfe_settings_setting_operator' => 'true',
											'acfe_settings_setting_value' => '',
										),
									),
								),
							),
							'acfe_validate' => array(
								'acfcloneindex' => array(
									'acfe_validate_location' => '',
									'acfe_validate_rules_and' => array(
										'acfcloneindex' => array(
											'acfe_validate_function' => 'value',
											'acfe_validate_operator' => '==',
											'acfe_validate_match' => '',
										),
									),
									'acfe_validate_error' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_6010413ee8145' => array(
					'key' => 'layout_6010413ee8145',
					'name' => 'column_4',
					'label' => '4 Text Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6010413ee8146',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_settings' => array(
								'acfcloneindex' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => array(
										'acfcloneindex' => array(
											'acfe_settings_setting_type' => 'required',
											'acfe_settings_setting_name' => '',
											'acfe_settings_setting_operator' => 'true',
											'acfe_settings_setting_value' => '',
										),
									),
								),
							),
							'acfe_validate' => array(
								'acfcloneindex' => array(
									'acfe_validate_location' => '',
									'acfe_validate_rules_and' => array(
										'acfcloneindex' => array(
											'acfe_validate_function' => 'value',
											'acfe_validate_operator' => '==',
											'acfe_validate_match' => '',
										),
									),
									'acfe_validate_error' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_601d2adaf7958' => array(
					'key' => 'layout_601d2adaf7958',
					'name' => '2_column_layout',
					'label' => '2 Column Layout',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_601d2b1ef7959',
							'label' => 'Clone',
							'name' => 'clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_601bd977c1cde',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_settings' => '',
						),
						array(
							'key' => 'field_601d2b41f795a',
							'label' => 'Clone',
							'name' => 'clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_601bd6ffef5ee',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_settings' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '147',
					'acfe_flexible_category' => array(
						0 => '2-Columns',
					),
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_60216424f8b51' => array(
					'key' => 'layout_60216424f8b51',
					'name' => 'cta',
					'label' => 'cta',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6021643ef8b52',
							'label' => 'Clone',
							'name' => 'clone',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'post_type' => array(
								0 => 'cptcta',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'save_custom' => 0,
							'save_post_status' => 'publish',
							'acfe_bidirectional' => array(
								'acfe_bidirectional_enabled' => '0',
							),
							'acfe_settings' => '',
							'acfe_validate' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => '',
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Module',
			'min' => '',
			'max' => '',
			'acfe_settings' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-page-builder.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'featured_image',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'page-building' => 'Page Building',
	),
	'modified' => 1613132586,
));

endif;