<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d6ffb5ba599d',
	'title' => 'Module: CTA - Links 01',
	'fields' => array(
		array(
			'key' => 'field_5f23fd7f49b38',
			'label' => 'Style / Layout',
			'name' => 'style',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'choices' => array(
				'images' => 'Images',
				'icons' => 'Icons',
			),
			'default_value' => 'links',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f27d9a27478b',
			'label' => 'Links / Files',
			'name' => 'links_files',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'ajde_events',
				3 => 'cookielawinfo',
				4 => 'cpt_careers',
				5 => 'cpt_newsevents',
				6 => 'cpt_staff',
				7 => 'cpt_page_content',
				8 => 'cpt_policies',
				9 => 'cpt_newsletter',
				10 => 'cpt_schools',
				11 => 'cpt_cta_content',
				12 => 'cpt_sidebar_content',
				13 => 'mec-events',
				14 => 'mec_calendars',
				15 => 'cpt_alerts',
				16 => 'cpt_courses',
				17 => 'cpt_course_content',
				18 => 'acfe-dbt',
				19 => 'acfe-form',
				20 => 'acfe-dop',
				21 => 'acfe-dpt',
				22 => 'acfe-dt',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'event_location',
				4 => 'event_organizer',
				5 => 'event_type',
				6 => 'event_type_2',
				7 => 'cpt_tax_newsfeed_categories',
				8 => 'cpt_tax_staff_categories',
				9 => 'cpt_tax_policies',
				10 => 'cpt_tax_career_cat',
				11 => 'mec_category',
				12 => 'cpt_tax_schools',
				13 => 'acf-field-group-category',
				14 => 'mec_label',
				15 => 'mec_location',
				16 => 'mec_organizer',
			),
			'choices' => array(
				'links' => 'Links',
				'files' => 'Files',
			),
			'default_value' => 'links',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f23feac9cdc3',
			'label' => 'Columns',
			'name' => 'columns',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f23fd7f49b38',
						'operator' => '==',
						'value' => 'icons',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'ajde_events',
				3 => 'cookielawinfo',
				4 => 'cpt_careers',
				5 => 'cpt_newsevents',
				6 => 'cpt_staff',
				7 => 'cpt_page_content',
				8 => 'cpt_policies',
				9 => 'cpt_newsletter',
				10 => 'cpt_schools',
				11 => 'cpt_cta_content',
				12 => 'cpt_sidebar_content',
				13 => 'mec-events',
				14 => 'mec_calendars',
				15 => 'cpt_alerts',
				16 => 'cpt_courses',
				17 => 'cpt_course_content',
				18 => 'acfe-dbt',
				19 => 'acfe-form',
				20 => 'acfe-dop',
				21 => 'acfe-dpt',
				22 => 'acfe-dt',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'event_location',
				4 => 'event_organizer',
				5 => 'event_type',
				6 => 'event_type_2',
				7 => 'cpt_tax_newsfeed_categories',
				8 => 'cpt_tax_staff_categories',
				9 => 'cpt_tax_policies',
				10 => 'cpt_tax_career_cat',
				11 => 'mec_category',
				12 => 'cpt_tax_schools',
				13 => 'acf-field-group-category',
				14 => 'mec_label',
				15 => 'mec_location',
				16 => 'mec_organizer',
			),
			'choices' => array(
				1 => 'One',
				2 => 'Two',
				3 => 'Three',
				4 => 'Four',
			),
			'default_value' => 2,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f23ff919cdc6',
			'label' => 'Text size',
			'name' => 'text_size',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f23fd7f49b38',
						'operator' => '==',
						'value' => 'icons',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'ajde_events',
				3 => 'cookielawinfo',
				4 => 'cpt_careers',
				5 => 'cpt_newsevents',
				6 => 'cpt_staff',
				7 => 'cpt_page_content',
				8 => 'cpt_policies',
				9 => 'cpt_newsletter',
				10 => 'cpt_schools',
				11 => 'cpt_cta_content',
				12 => 'cpt_sidebar_content',
				13 => 'mec-events',
				14 => 'mec_calendars',
				15 => 'cpt_alerts',
				16 => 'cpt_courses',
				17 => 'cpt_course_content',
				18 => 'acfe-dbt',
				19 => 'acfe-form',
				20 => 'acfe-dop',
				21 => 'acfe-dpt',
				22 => 'acfe-dt',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'event_location',
				4 => 'event_organizer',
				5 => 'event_type',
				6 => 'event_type_2',
				7 => 'cpt_tax_newsfeed_categories',
				8 => 'cpt_tax_staff_categories',
				9 => 'cpt_tax_policies',
				10 => 'cpt_tax_career_cat',
				11 => 'mec_category',
				12 => 'cpt_tax_schools',
				13 => 'acf-field-group-category',
				14 => 'mec_label',
				15 => 'mec_location',
				16 => 'mec_organizer',
			),
			'choices' => array(
				'Small' => 'Small',
				'medium' => 'Medium',
				'large' => 'Large',
			),
			'default_value' => 'medium',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f23ffd29cdc7',
			'label' => 'Text colour',
			'name' => 'text_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f23fd7f49b38',
						'operator' => '==',
						'value' => 'icons',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_5f240d459d905',
			'label' => 'Module margin',
			'name' => 'module_margin',
			'type' => 'select',
			'instructions' => 'set the height above and below the module in px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'choices' => array(
				'none' => 'None',
				'small' => 'Small',
				'medium' => 'Medium',
				'large' => 'Large',
			),
			'default_value' => 'medium',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d6ffb8be3db5',
			'label' => 'Images',
			'name' => 'links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f23fd7f49b38',
						'operator' => '==',
						'value' => 'images',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6ffc3de3db6',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image_aspect_ratio_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'crop_type' => 'aspect_ratio',
					'aspect_ratio_width' => 563,
					'aspect_ratio_height' => 362,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5d84fe9b98070',
					'label' => 'Overlay opacity',
					'name' => 'overlay_opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 6,
					'min' => 1,
					'max' => 9,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5d6ffdb3e3db7',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d7000a8e3db8',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f27d9a27478b',
								'operator' => '==',
								'value' => 'links',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
				),
				array(
					'key' => 'field_5f27d9f1446c2',
					'label' => 'File',
					'name' => 'file',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f27d9a27478b',
								'operator' => '==',
								'value' => 'files',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'uploader' => 'wp',
				),
			),
		),
		array(
			'key' => 'field_5f2403b27bc8a',
			'label' => 'Icons',
			'name' => 'files',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f23fd7f49b38',
						'operator' => '==',
						'value' => 'icons',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5f2403b37bc8c',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_thumbnail' => 0,
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'default_value' => '',
					'uploader' => 'wp',
				),
				array(
					'key' => 'field_5f2403b37bc8e',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'ajde_events',
						3 => 'cookielawinfo',
						4 => 'cpt_careers',
						5 => 'cpt_newsevents',
						6 => 'cpt_staff',
						7 => 'cpt_page_content',
						8 => 'cpt_policies',
						9 => 'cpt_newsletter',
						10 => 'cpt_schools',
						11 => 'cpt_cta_content',
						12 => 'cpt_sidebar_content',
						13 => 'mec-events',
						14 => 'mec_calendars',
						15 => 'cpt_alerts',
						16 => 'cpt_courses',
						17 => 'cpt_course_content',
						18 => 'acfe-dbt',
						19 => 'acfe-form',
						20 => 'acfe-dop',
						21 => 'acfe-dpt',
						22 => 'acfe-dt',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'event_location',
						4 => 'event_organizer',
						5 => 'event_type',
						6 => 'event_type_2',
						7 => 'cpt_tax_newsfeed_categories',
						8 => 'cpt_tax_staff_categories',
						9 => 'cpt_tax_policies',
						10 => 'cpt_tax_career_cat',
						11 => 'mec_category',
						12 => 'cpt_tax_schools',
						13 => 'acf-field-group-category',
						14 => 'mec_label',
						15 => 'mec_location',
						16 => 'mec_organizer',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f2403b37bc8f',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'ajde_events',
						3 => 'cookielawinfo',
						4 => 'cpt_careers',
						5 => 'cpt_newsevents',
						6 => 'cpt_staff',
						7 => 'cpt_page_content',
						8 => 'cpt_policies',
						9 => 'cpt_newsletter',
						10 => 'cpt_schools',
						11 => 'cpt_cta_content',
						12 => 'cpt_sidebar_content',
						13 => 'mec-events',
						14 => 'mec_calendars',
						15 => 'cpt_alerts',
						16 => 'cpt_courses',
						17 => 'cpt_course_content',
						18 => 'acfe-dbt',
						19 => 'acfe-form',
						20 => 'acfe-dop',
						21 => 'acfe-dpt',
						22 => 'acfe-dt',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'event_location',
						4 => 'event_organizer',
						5 => 'event_type',
						6 => 'event_type_2',
						7 => 'cpt_tax_newsfeed_categories',
						8 => 'cpt_tax_staff_categories',
						9 => 'cpt_tax_policies',
						10 => 'cpt_tax_career_cat',
						11 => 'mec_category',
						12 => 'cpt_tax_schools',
						13 => 'acf-field-group-category',
						14 => 'mec_label',
						15 => 'mec_location',
						16 => 'mec_organizer',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => '',
					'acfe_textarea_code' => 0,
				),
				array(
					'key' => 'field_5f27da25446c3',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f27d9a27478b',
								'operator' => '==',
								'value' => 'links',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
				),
				array(
					'key' => 'field_5f2403b37bc91',
					'label' => 'File',
					'name' => 'file',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f27d9a27478b',
								'operator' => '==',
								'value' => 'files',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'uploader' => 'wp',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 66,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'cta' => 'CTA',
	),
	'modified' => 1615765555,
));

endif;