<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d42c9084f29e',
	'title' => 'Module: Gallery',
	'fields' => array(
		array(
			'key' => 'field_5d42c90f10ddb',
			'label' => 'Gallery images',
			'name' => 'gallery_images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 1,
			'max' => 8,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d42c93910ddc',
					'label' => 'Category name',
					'name' => 'category_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d655a791a74e',
					'label' => 'Gallery type',
					'name' => 'gallery_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'gallery' => 'Image Gallery',
						'video' => 'Video gallery',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d42c94610ddd',
					'label' => 'Category images',
					'name' => 'category_images',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d655a791a74e',
								'operator' => '==',
								'value' => 'gallery',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'min' => '',
					'max' => '',
					'insert' => 'append',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
					'return_format' => 'array',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_5d655ae4de111',
					'label' => 'Videos',
					'name' => 'videos',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d655a791a74e',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'row',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5d655b1ade114',
							'label' => 'Video type',
							'name' => 'video_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'youtube' => 'Youtube',
								'vimeo' => 'Vimeo',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'acfe_validate' => '',
							'acfe_update' => '',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5d65864d99eae',
							'label' => 'Vimeo Instructions',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5d655b1ade114',
										'operator' => '==',
										'value' => 'vimeo',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => 'Please copy paste the code from the Vimeo video url. For example please see this video url: https://vimeo.com/355402411. The code we need is "355402411".',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
						array(
							'key' => 'field_5d655b0ede113',
							'label' => 'Vimeo Video ID',
							'name' => 'vimeo_video_id',
							'type' => 'vimeo',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5d655b1ade114',
										'operator' => '==',
										'value' => 'vimeo',
									),
								),
							),
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'return_format' => 'id',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d6585ed6398b',
							'label' => 'Youtube Instructions',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5d655b1ade114',
										'operator' => '==',
										'value' => 'youtube',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => 'Please copy paste the code from the youtube video url. For example please see this video url: https://www.youtube.com/watch?v=XbNTv1x1HmE#action=share. The code we need is "XbNTv1x1HmE".',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
						array(
							'key' => 'field_5d655b46de115',
							'label' => 'Youtube video code',
							'name' => 'youtube',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5d655b1ade114',
										'operator' => '==',
										'value' => 'youtube',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d655b03de112',
							'label' => 'Preview image',
							'name' => 'preview_image',
							'type' => 'image_aspect_ratio_crop',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'aspect_ratio_width' => 800,
							'aspect_ratio_height' => 800,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
							'crop_type' => 'aspect_ratio',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 55,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'gallery' => 'Gallery',
	),
	'modified' => 1615765508,
));

endif;