<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60547e5be74c2',
	'title' => 'Module: Hero Narrow',
	'fields' => array(
		array(
			'key' => 'field_60547e5bf3fdf',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_60547e5c075d5',
			'label' => 'Background Overlay',
			'name' => 'background_overlay',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_60547e5c30a77',
					'label' => 'Overlay Direction',
					'name' => 'overlay_direction',
					'type' => 'range',
					'instructions' => 'Enter angle for Overlay Direction ( 0 = top) (90 = Right)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_60547e5c3467f',
					'label' => 'Fade Colour',
					'name' => 'fade_colour',
					'type' => 'extended-color-picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'color_palette' => '',
					'hide_palette' => 0,
				),
				array(
					'key' => 'field_60547e5c3829a',
					'label' => 'Solid Colour',
					'name' => 'solid_colour',
					'type' => 'extended-color-picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'color_palette' => '',
					'hide_palette' => 0,
				),
			),
		),
		array(
			'key' => 'field_60547e5c0ede9',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60547e5c129fd',
			'label' => 'Heading Animation',
			'name' => 'heading_animation',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'fade' => 'Fade',
				'scale-up' => 'Fade & Scale Up',
				'scale-down' => 'Fade & Scale Down',
				'slide-top' => 'Slide Top',
				'slide-bottom' => 'Slide Bottom',
				'slide-left' => 'Slide Left',
				'slide-right' => 'Slide Right',
				'kenburns' => 'Scale Slowly No Fade',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'allow_custom' => 0,
			'search_placeholder' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_60547e5c16607',
			'label' => 'Animation Delay',
			'name' => 'heading_animation_delay',
			'type' => 'text',
			'instructions' => '1000 = 1 Second',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 500,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'hero' => 'Hero',
	),
	'modified' => 1616151065,
));

endif;